# Generated by Django 4.0.2 on 2022-02-27 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilization',
            fields=[
                ('civilization_id', models.AutoField(primary_key=True, serialize=False)),
                ('civilization_name', models.CharField(max_length=25)),
                ('civilization_meta', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('map_id', models.AutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_name', models.CharField(max_length=50)),
                ('match_uuid', models.CharField(max_length=50)),
                ('match_datetime_start', models.DateTimeField()),
                ('match_duration', models.DateTimeField()),
                ('match_team_win', models.SmallIntegerField(null=True)),
                ('match_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.map')),
            ],
            options={
                'ordering': ['match_datetime_start'],
            },
        ),
        migrations.CreateModel(
            name='MatchTag',
            fields=[
                ('match_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_tag_name', models.CharField(max_length=25)),
                ('match_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50, unique=True)),
                ('player_rating', models.IntegerField(null=True)),
                ('player_api_id', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['player_rating'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PlayersInMatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pim_civilization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.civilization')),
                ('pim_match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.match')),
                ('pim_player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.player')),
                ('pim_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.teams')),
            ],
        ),
        migrations.CreateModel(
            name='MatchTagging',
            fields=[
                ('match_tagging', models.AutoField(primary_key=True, serialize=False)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.match')),
                ('match_tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.matchtag')),
            ],
        ),
    ]
